version: "2"
linters:
  default: all
  disable:
    - depguard
    - dupl
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocyclo
    - godox
    - goheader
    - gomodguard
    - gosmopolitan
    - grouper
    - inamedparam
    - loggercheck
    - maintidx
    - nlreturn
    - nonamedreturns
    - promlinter
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - varnamelen
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    cyclop:
      max-complexity: 30
    exhaustive:
      default-signifies-exhaustive: true
    govet:
      enable-all: true
    importas:
      alias:
        - pkg: go.expect.digital/translate/pkg/pb/translate/v1
          alias: translatev1
    ireturn:
      allow:
        - anon
        - error
        - empty
        - generic
        - stdlib
        - (or|er)$
        - Literal
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
