linters:
  enable-all: true
  disable:
    - depguard
    - dupl
    - err113
    - execinquery
    - exhaustruct
    - forbidigo
    - funlen
    - gci
    - ginkgolinter
    - goconst
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - godox
    - gofmt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - gosmopolitan
    - grouper
    - inamedparam
    - loggercheck
    - maintidx
    - nlreturn
    - nonamedreturns
    - promlinter
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - varnamelen
    - wastedassign
    - whitespace
    - zerologlint
linters-settings:
  cyclop:
    max-complexity: 30
  exhaustive:
    default-signifies-exhaustive: true
  govet:
    enable-all: true
  importas:
    alias:
      - pkg: go.expect.digital/translate/pkg/pb/translate/v1
        alias: translatev1
  ireturn:
    allow:
      - anon
      - error
      - empty
      - generic
      - stdlib
      - (or|er)$
      - Literal # false reporting in parseLiteral() by nolintlint
  predeclared:
    ignore: ""
