name: CI

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23.x", "1.24.x", "1.25.0-rc2"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -v ./...
      - name: golangci-lint
        # golangci-lint may not support Go release candidates, so we skip this step for RC builds.
        if: "!contains(matrix.go-version, 'rc')"
        uses: golangci/golangci-lint-action@v7
        with:
          # v2.0.2 appears to be an invalid version. Using a recent one.
          version: v1.59.1
