name: CI

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22.x", "1.23.x", "1.24.x"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.1
